config/routes.rb
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  # GET /about
  get "about", to: "about#index", as: :about

  # GET /password
  get "password", to: "passwords#edit", as: :edit_password
  # PATCH /password
  patch "password", to: "passwords#update"

  # GET /password/reset
  get "password/reset", to: "password_resets#new"
  # POST /password/reset
  post "password/reset", to: "password_resets#create"

  # GET /password/reset/edit
  get "password/reset/edit", to: "password_resets#edit"
  # PATCH /password/reset/edit
  patch "password/reset/edit", to: "password_resets#update"

  # GET /sign_up
  get "sign_up", to: "registrations#new"
  # POST /sign_up
  post "sign_up", to: "registrations#create"

  # GET /sign_in
  get "sign_in", to: "sessions#new"
  # POST /sign_in
  post "sign_in", to: "sessions#create"

  # DELETE /logout
  delete "logout", to: "sessions#destroy"
  # GET /
  root to: "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
  # https://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html
  has_secure_password

  validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address" }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Before every action load the current user
  before_action :set_current_user

  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end

  def require_user_logged_id!
    redirect_to sign_in_path, alert: "You must be signed in to do that!" if Current.user.nil?
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    # flash[:notice] = "Debug"
    # flash[:alert] = "Debug"
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])

    if (@user.present?)
      # send email
      PasswordMailer.with(user: @user).reset.deliver_later
    end

    redirect_to root_path, notice: "Email to reset password sent."
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: "password_reset")
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to sign_in_path, alert: "Your token has expired. Please try again."
  end

  def update
    @user = User.find_signed!(params[:token], purpose: "password_reset")
    if @user.update(password_params)
      redirect_to sign_in_path, notice: "Your password was reset successfully!"
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :require_user_logged_id!

  def edit
  end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: "Password updated"
    else
      render :edit, status: 422
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Successfully created account"
    else
      render :new, status: 422
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in successfully"
    else
      flash[:alert] = "Invalid Email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- csrf_meta_tags -->
    <%= csrf_meta_tags %>
    <!-- end csrf_meta_tags -->
    <!-- csp_meta_tag -->
    <%= csp_meta_tag %>
    <!-- end csp_meta_tag -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css" integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<h1>Main page!</h1>

app/views/password_resets/edit.html.erb
<h1>Reset your password</h1>
<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]), local: true, data: { turbo: false } do |form| %>
  <% if form.object.errors.any? %>
    <div class="alert alert-danger">
      <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>
  <div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.submit "Reset password", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot password?</h1>
<%= form_with url: password_reset_path, local: true, data: { turbo: false } do |form| %>
  <div class="mb-3">
    <%= form.label :email %>
    <%= form.email_field :email, class: "form-control", required: true, placeholder: "Es. mario.rossi@gmail.com" %>
  </div>
  <div class="mb-3">
    <%= form.submit "Reset password", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<div class="fixed-bottom container">
  <%# Flash notice %>
  <% if flash[:notice] %>
    <div class="alert alert-info hideMe" role="alert">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <%# Flash alert %>
  <% if flash[:alert] %>
    <div class="alert alert-warning hideMe" role="alert">
      <%= flash[:alert] %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<% 
def active_class(link_path)
    current_page?(link_path) ? "active" : ""
end
%>
<nav class="navbar navbar-expand-lg bg-body-tertiary mb-3">
  <div class="container">
    <%= link_to "Scheduled tweets", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%# Home %>
        <li class="nav-item <%= active_class(root_path) %>">
          <%= link_to "Home", root_path, class:"nav-link" %>
        </li>
        <%# About %>
        <li class="nav-item <%= active_class(about_path) %>">
          <%= link_to "About", about_path, class:"nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav mb-2 mb-lg-0 d-flex">
        <% if Current.user %>
          <%= link_to Current.user.email, edit_password_path, class: "nav-link" %>
          <%= button_to "<i class='bi bi-box-arrow-right'></i>".html_safe, logout_path, class:"btn", method: :delete, title: "logout" %>
        <% else %>
          <%# Signup %>
          <li class="nav-item <%= active_class(sign_up_path) %>">
            <%= link_to "Signup", sign_up_path, class:"nav-link" %>
          </li>
          <%# Signin %>
          <li class="nav-item <%= active_class(sign_in_path) %>">
            <%= link_to "Sign in", sign_in_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>